{"uuid": "7f5653e1-c46e-4b25-9c78-77bbae1763f7", "children": ["7a08e77c-46cf-4fa4-9f19-253c7dafa8b8"], "befores": [{"name": "suitinit", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: A session is either terminated or not started\n\n", "trace": "  File \"/usr/local/lib/python3.9/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/likunyu/project/521-uiautomation/tests/test_vedio/conftest.py\", line 22, in suitinit\n    base_business.login(action,'user1')\n  File \"/Users/likunyu/project/521-uiautomation/lib/reuse_business/base_business.py\", line 15, in login\n    up.用户中心.pageinto(action)\n  File \"/Users/likunyu/project/521-uiautomation/lib/pages/userpage.py\", line 18, in pageinto\n    p.特卖首页.pageinto(action)\n  File \"/Users/likunyu/project/521-uiautomation/lib/pages/productpage.py\", line 27, in pageinto\n    action.start_activity(self.activity)\n  File \"/Users/likunyu/project/521-uiautomation/base/action.py\", line 57, in start_activity\n    self.driver.start_activity(self.env.appium.get(\"appPackage\"), app_activity, **opts)\n  File \"/usr/local/lib/python3.9/site-packages/appium/webdriver/extensions/android/activities.py\", line 63, in start_activity\n    self.execute(Command.START_ACTIVITY, data)\n  File \"/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/lib/python3.9/site-packages/appium/webdriver/errorhandler.py\", line 31, in check_response\n    raise wde\n  File \"/usr/local/lib/python3.9/site-packages/appium/webdriver/errorhandler.py\", line 26, in check_response\n    super().check_response(response)\n  File \"/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1647949014537, "stop": 1647949014562}], "start": 1647949014537, "stop": 1647949014599}